name: acadsys
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.3
  google_sign_in: ^6.2.1
  
  # UI/UX
  lottie: ^3.1.2
  animated_text_kit: ^4.2.2
  line_icons: ^2.0.3
  convex_bottom_bar: ^3.2.0

  # Global State
  flutter_bloc: ^8.1.6
  go_router: ^14.3.0
  equatable: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
